### ISSUE TITLE
Duplicate installer version 6.0.0

### ISSUE THREAD

**Issue by erwinkramer** [sandroasp/BizTalk-Scheduled-Task-Adapter#1]
2 different installers exist for version 6.0.0. Your one and the one from Codeplex. I see that the behaviour is different for the adapter (bug fix for too many messages in schedule). 

So why is it named 6.0.0 and not 6.1 for example? Very confusing.

**Comment by sandroasp** [comment]
Codeplex is deprecated. But thanks for the feedback. I will try to not repeat the same mistake
