### ISSUE TITLE
Timedrift when using timespan functionality

### ISSUE THREAD

**Issue by JimmyHjelte** [sandroasp/BizTalk-Scheduled-Task-Adapter#2]
Hi, I have a customer that uses the schedule adapter with a 1 minute intervall set but after a while there is a gap on the receiving  system when there is no data. I suspect that the adapter is  affected by the execution time and that after a while it will skip over  a minute.

I looked at the sourcecode from codeplex as I could not find it here on Github , is this still the one in use ?

The GetNextActivationTime() method uses DateTime.UtcNow instead of the time when it was last triggerd so it all depends on when GetNextActivationTime() is called.

Why is that nextactivated is set to GetNextActivationTime(now) and not the more correct one  GetNextActivationTime(lastActivated.Value) ?

        public DateTime GetNextActivationTime()
		{
            //DateTime now = DateTime.Now;                       
            //Add 2016 new schedule capabitities
            DateTime now = DateTime.UtcNow;
            if (!lastActivated.HasValue)
            {
                nextActivated = GetNextActivationTime(now);
                return nextActivated.Value;
            }
            //if (now <= lastActivated)
            //Add 2016 new schedule capabitities    
            if (now < lastActivated)
            {
                nextActivated = GetNextActivationTime(lastActivated.Value);
                return nextActivated.Value;
            }
            nextActivated = GetNextActivationTime(now);
            return nextActivated.Value;            
        }

**Comment by fernandodsanjos** [comment]
We replaced all UtfNow to Now and then it worked as it should

**Comment by sandroasp** [comment]
This issue is solved on the latest version published: 7.0.2: https://blog.sandro-pereira.com/2021/03/10/biztalk-scheduled-task-adapter-7-0-2-is-now-available-for-biztalk-server-2020/
