### ISSUE TITLE
Timly Schedule Start Time (and Date) doest not work correct

### ISSUE THREAD

**Issue by maiklange** [sandroasp/BizTalk-Scheduled-Task-Adapter#4]
We use a timely schedule to start the bitzalkapplication every 5 minutes. 

Today we've updated our BizTalkaplication and update the start date to today (28.08.2019). After we started the application over 70000 instances created by the adapter. 

I suppose that the iadapter uses the initial start date instead of the current one. 

Thanks

**Comment by sandroasp** [comment]
This issue is solved on the latest version published: 7.0.2: https://blog.sandro-pereira.com/2021/03/10/biztalk-scheduled-task-adapter-7-0-2-is-now-available-for-biztalk-server-2020/
