### ISSUE TITLE
In certain cases task won't trigger in set time with Timespan with Biztalk 2016

### ISSUE THREAD

**Issue by phuuskon** [sandroasp/BizTalk-Scheduled-Task-Adapter#5]
In Biztalk 2016 when using Timespan task won't trigger in set time if trigger time or date is set to past time.
Also disabling/enabling of the rloc or restarting host instance will break the set trigger time.
These cases the time for the trigger seem to come from current server time.
More info about the behavior here: https://www.pekkahuuskonen.com/2019/12/schedule-task-to-future-in-biztalk/

**Comment by phuuskon** [comment]
Hmm... Some reverse engineering and looking at old code at codeplex archive tells me that this "bug" is actually a feature. Got to modify a special version for myself :)

**Comment by phuuskon** [comment]
Modified a version to myself that behaves like I was used to this adapter to behave. More info here: https://www.pekkahuuskonen.com/2019/12/schedule-task-to-future-in-biztalk_pt2/

**Comment by sandroasp** [comment]
This issue is solved on the latest version published: 7.0.2: https://blog.sandro-pereira.com/2021/03/10/biztalk-scheduled-task-adapter-7-0-2-is-now-available-for-biztalk-server-2020/ soon I will release the version to BTS2016
