### ISSUE TITLE
Using a start date of Today with a Timespan interval triggers unlimited messages

### ISSUE THREAD

**Issue by Rumbers** [sandroasp/BizTalk-Scheduled-Task-Adapter#6]
1. Create a new receive location
2. Set the start date and time to a few minutes in the future
3. Timespan Interval 1 hour, or 20 minutes
Expected: a single receive event at that time
Actual: Watch as thousands of messages bring your environment to its knees

Changing the start date to the past will resolve the issue. Good luck with the clean up.

**Comment by Lautaro** [comment]
I have a similar issue. If interval is one hour there is no problem. If interval is less then the _first_ timed event will result in several calls. Each call after that is only one as expected. 
30 sec interval = 120 messages
1min interval = 60 messages 
5 min interval =12 messages
11 min interval =5 messages
18 min interval =3messages

**Comment by sandroasp** [comment]
What is the time zone configured in your servers? 
I try all of these settings and the adapter is working properly in several servers.

**Comment by sandroasp** [comment]
This issue is solved on the latest version published: 7.0.2: https://blog.sandro-pereira.com/2021/03/10/biztalk-scheduled-task-adapter-7-0-2-is-now-available-for-biztalk-server-2020/
