### ISSUE TITLE
7.0 for BTS 2020?

### ISSUE THREAD

**Issue by swalde** [sandroasp/BizTalk-Scheduled-Task-Adapter#7]
My klient is an On-Prem only kind of place.

When will there be an 7,0 for BizTalk 2020? I havee problems using BSTA 6.0 for 2016 on a BTS 2020

**Comment by maiklange** [comment]
I have found a workaround: https://datapassion.de/dpnews/biztalk-scheduled-task-adapter-biztalk-2020 

maybe this helps...

I hope there will be an adjustment

**Comment by sandroasp** [comment]
There is a new version of the adapter published full supported for BTS 2016 and 2020
